---
- name: Install Rustup in Fedora
  ansible.builtin.shell: |
    set -o pipefail
    curl https://sh.rustup.rs -sSf | sh -s -- -y

- name: Install Rust deps
  become: true
  ansible.builtin.dnf:
    name:
      - openssl
      - openssl-devel
      - musl-*
    state: present

- name: Add rustup components
  ansible.builtin.shell: |
    set -o pipefail
    rustup update
    rustup toolchain add nightly
    rustup component add rust-analyzer
    rustup component add rust-src
    rustup component add rustfmt
    rustup component add rustc-dev
    rustup component add clippy

- name: Add rust targets
  ansible.builtin.shell: |
    set -o pipefail
    rustup target add x86_64-unknown-linux-musl
    rustup target add wasm32-unknown-emscripten

- name: Install cargo tools
  ansible.builtin.shell: |
    set -o pipefail
    cargo install cargo-edit
    cargo install cargo-audit
    cargo install stylua
