---
- name: Install python tooling
  become: true
  dnf:
    name:
      - python3
      - python3-devel
      - pipx
      - dnf-plugins-core

- name: Python3 build deps
  become: true
  shell: |
    dnf builddep -y python3

- name: Update pip
  become: true
  shell: |
    python3 -m pip install --upgrade pip

- name: Common Python libraries
  become: false
  shell: |
    python3 -m pip install --user build pylint black isort mypy ipython ipdb pydump \
      numpy pandas scipy matplotlib sympy nose \
      jupyter jupyterlab

- name: Pipx
  become: false
  shell: |
    pipx install python-language-server pdm ruff
