---
- name: Disallow SSH password authentication
  become: true
  block:
    - name: collect sshd configs
      ansible.builtin.find:
        paths: /etc/ssh/sshd_config.d
        patterns: "*.conf"
        file_type: file
      register: collected_info

    - name: update sshd conf
      copy:
        dest: "{{ item.path }}"
        content: "PasswordAuthentication no\n"
      with_items: "{{ collected_info.files }}"
      register: update_result

    - name: restart sshd
      service:
        name: sshd
        state: restarted
      when: update_result.changed is true
