- name: enable Fedora Copr for Bottom
  become: true
  community.general.copr:
    name: atim/bottom
    state: enabled

- name: Install CLI utils in Fedora
  become: true
  dnf:
    name:
      - bat
      - dutree
      - gitui
      - hyperfine
      - procs
      - sd
      - tealdeer
      - tokei
      - tmux
      - screen
      - zoxide
      - skim
      - ranger
      - bottom
      - exa
      - git-delta
      - ripgrep
    state: present

#      - fd
#      - dust
#      - ffizer
#      - git-irbt
#      - bandwhich
#      - grex
#      - broot
#      - delta
#      - difft
#      - bingrep
#      - basic-http-server
