---
- name: Install media
  become: true
  dnf:
    name:
      - cheese
      - vlc
      - v4l-utils
      - blender
      - gimp
      - inkscape
      - speech-dispatcher
      - speech-dispatcher-utils
    state: present
  when: ansible_distribution == "Fedora"

- name: terminal
  become: true
  dnf:
    name:
      - tmux
      - alacritty
    state: present
  when: ansible_distribution == "Fedora"

- name: Clone TPM repository
  git:
    repo: 'https://github.com/tmux-plugins/tpm.git'
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
  become: false
  tags: tmux

- name: Common WM
  become: true
  dnf:
    name:
      - dmenu
      - waybar
      - wayvnc
      - system-config-printer
      - system-config-*
      - dunst
      - xbacklight
      - feh
      - conky
      - blueman
      - maim
      - xclip
      - xdotool
      - volumeicon
      - gammastep
      - grim
      - slurp
      - bemenu

- name: i3
  become: true
  dnf:
    name:
      - i3
      - i3status
      - i3lock
    state: present
  when: ansible_distribution == "Fedora"

- name: SwayWM
  become: true
  dnf:
    name:
      - sway
    state: present
  when: ansible_distribution == "Fedora"

- name: HyprLand
  become: true
  dnf:
    name:
      - hyprland
      - hyprland-devel
    state: present
  when: ansible_distribution == "Fedora"
