---
- name: Install C/C++ toolchains in Fedora
  become: true
  dnf:
    name:
      - clang
      - clang-devel
      - clang-libs
      - clang-tools-extra
      - clang-tools-extra-devel
      - gcc
      - g++
      - automake
      - autoconf
      - cmake
      - ninja-build
      - binutils
      - binutils-devel
      - strace
      - perf
      - gperf
      - bison
      - flex
      - gdb
      - zig
    state: present
  when: ansible_distribution == "Fedora"
